mjcrouch/vscode-perforce

src/test/suite/model.test.ts
mac tests on azure pipelines seem to be slow and fail on the beforeEach stage when doing work involving perforce commands. Try doubling timeout to reduce rate of failure
=> increase timeout to 4000 for mac tests

.vscode/tasks.json, CONTRIBUTING.md, package-lock.json, package.json, src/CommandLimiter.ts, src/ConfigService.ts, src/Debounce.ts, src/Display.ts, src/PerforceService.ts, src/ScmProvider.ts, src/extension.ts, src/scm/Model.ts, src/test/helpers/helpers.d.ts, src/test/helpers/p4Commands.ts, src/test/runUnitTest.ts, src/test/suite/StubPerforceService.ts, src/test/suite/model.test.ts, src/test/suite/unit/CommandLimiter.test.ts, src/test/suite/unit/Debounce.test.ts, src/test/suite/unit/index.ts, test-fixtures/core/.vscode/settings.json
Fixes #12 
Improves refresh performance in a few ways:
- Runs a single describe to get the list of shelved files for all changelists, instead of running one for each changelist in turn
- Runs a single fstat to get the details for shelved files, instead of running one for each changelist in turn (may be split into chunks)
- Gets the shelved and open files using Promise.all so that they can run asynchronously
- P4 info is only used to get the client name in case the client is being defaulted and is not explicitly defined. Generally, this could probably be done once, though there is potential for the client returned by p4 info to change during run time.
For now, I've changed it so that it only checks again when manually refreshing, and not when a user action like shelve or edit has been run, …
=> Refresh performance

CONTRIBUTING.md, package-lock.json, package.json, src/test/runTest.ts
This allows a watch-build of the integration tests using a virtual display on linux
=> Add watchintegration-linux command

src/ScmProvider.ts, src/scm/Model.ts, src/test/runTest.ts, src/test/suite/StubPerforceService.ts, src/test/suite/model.test.ts
Fixes #4 
Refactors SaveToChangelist into smaller units and implements a new option to move to a "New changelist..." in the dropdown when selecting the changelist to move to.
=> Move to new changelist

package.json, src/Display.ts, src/ScmProvider.ts, src/scm/Model.ts, src/test/suite/StubPerforceService.ts, src/test/suite/model.test.ts
fixes #3
Introduces "Attach job..." and "Remove job..." to the context menu for jobs.
* Attach job presents an input box requesting a job number
* Remove job presents a list of currently attached jobs, selecting one removes the job
=> Add commands to attach jobs to changelists

package.json, src/ScmProvider.ts, src/scm/Model.ts, src/test/suite/model.test.ts
Fixes #17 
Allows a single shelved file to be deleted from a changelist.
Also prevents "revert file" from being used on a shelved file
=> Delete shelved file

src/ContentProvider.ts, src/ScmProvider.ts, src/Utils.ts, src/scm/Model.ts, src/scm/Resource.ts, src/test/suite/StubPerforceService.ts, src/test/suite/model.test.ts
- The gutter decorations for diffing have been corrected when a revision other than the latest is open for edit
- Diffing from the scm view is against the working revision instead of the latest revision. For moved files, it is against the working revision of the moved-from file
- The diff titles are updated to much more concise versions
Also prevents spurious output during test runs (at least some of it, if not all), by stubbing the refresh function
Fixes #6 
Fixes #26
=> Diff against working / have revision

package.json, src/Display.ts, src/extension.ts
The log output is always initialised as long as activation mode is not set to 'off' - and additional logging is provided to describe what's happening. This might help people understand what's happening. Or at least, provides useful output for when an issue is raised.
It doesn't change any initialisation behaviour so any existing issues with the setup will still be present
The extension watches for changes to the config that might require a restart and warns the user that a restart is required. (TODO - make some of these settings actually not require a restart)
fixes #7
=> Start improving setup experience

package.json
* Removes commands that are not intended to be used in the command palette, using a when clause
* Most of the useful commands already have duplicate versions that work on a file open in the editor - which are not removed
* Slightly improves descriptions for some remaining commands
fixes #24
=> Hide unusable commands from the command palette

src/Debounce.ts, src/Display.ts, src/FileSystemListener.ts, src/PerforceCommands.ts, src/PerforceService.ts, src/ScmProvider.ts, src/extension.ts, src/scm/Model.ts, src/test/suite/model.test.ts, src/test/suite/unit/Debounce.test.ts
Originally, when edit on file modify / save was enabled, the extension contained some code to run commands and check perforce before opening the file for edit. This was removed due to https://github.com/stef-levesque/vscode-perforce/issues/110 - however, we do have the information about what's open and can avoid opening the file if we already have it open.
Potentially this means we may not open a file for edit if it has been submitted externally and the user tries to modify it again. This can be resolved with a manual refresh (or really any other operation that results in a refresh) or by just manually using the "edit" command from the p4 command menu.
This seems like an acceptable trade-off.
Could consider refreshing the scm provider automatically if a conflict is detected when the …
=> Edit on file mod / save - don't open already open files

src/ContentProvider.ts, src/ScmProvider.ts, src/Utils.ts, src/scm/Model.ts, src/test/suite/StubPerforceService.ts, test-fixtures/core/.vscode/settings.json
This prevents 'stuck' content providers that never resolve because perforce has no 'have' revision. This caused issues such as:
* gutter decorations would not update after submitting a new file, because it was still trying to resolve the original gutter decorations
* diffs wold sit spinning forever if there was a reason the diff was impossible, instead of showing an error message
However, the implication of fixing this is that when `provideOriginalResource` rejects (or returns undefined) - it keeps trying to get the original resource every time you change the file, which results in spamming the print command. As a result, implemented a `p4 have` check for each file before returning a resource uri. The result of the have check is cached until the next refresh, so we don't keep spamming the …
=> Correctly reject promises in content provider

src/api/PerforceApi.ts, src/scm/Model.ts, src/test/suite/perforceApi.test.ts
When there are no changelists, it was attempting to run describe without any arguments
=> Fix failure to load files when there are no changelists

package.json, src/PerforceCommands.ts, src/ScmProvider.ts, src/Utils.ts, src/api/PerforceApi.ts, src/scm/Model.ts, src/test/helpers/StubPerforceModel.ts, src/test/suite/model.test.ts, src/test/suite/perforceApi.test.ts, src/test/suite/perforceCommands.test.ts
Adds a "Submit selected files..." context menu item for files in the default changelist only, to submit them in a new changelist
Not ready for merge yet - also want to add a command to the command palette / status bar menu to submit a single file to the default changelist
Fixes #20
=> Add command to submit selected files from the default changelist

src/PerforceService.ts
* Perforce server on windows returns \r\n line endings in p4 info
* The parsed client root incorrectly ended in \r
=> Fix issue with windows line endings

src/scm/Model.ts, src/test/helpers/StubPerforceModel.ts, src/test/suite/model.test.ts
The code to find the underlying file for a shelved file assumed there is always a `clientFile` property in the fstat output, which is not the case if the shelved file is for a path that is not in the client view
fixes #50
=> Handle shelved files without clientFile mapping

package.json
Allows users to conditionally hide the submit icon next to the change-list descriptions. Makes it a bit tougher to accidentally submit a changelist.
See examples below:
`hideSubmitIcon == true` - context menu option still exists, button does not display next to CL description.
`hideSubmitIcon == false`
=> Adds `perforce.hideSubmitIcon` setting

src/Display.ts, src/PerforceCommands.ts, src/PerforceService.ts, src/Utils.ts, src/test/helpers/StubPerforceModel.ts, src/test/suite/perforceApi.test.ts
This slightly improves the `directoryOverride` by centralizing the logic, without having it spread over multiple places.
There were only a few usages of directoryOverride and they were all doing the same thing - if and only if there were no workspace folders, it was adding the -d option to commands, using the directory of the relevant file (this is a very difficult situation to get into, as the extension does not activate if there is no folder opened)
Perforce uses -d to override the cwd / PWD environment - so instead we can just spawn the process in the right place with the right environment. Tested working on linux; I still need to test this on windows.
Now, it always uses the directory if there is no workspace for the file, i.e. if you open a file that is not in your workspace, you …
=> Always run in the directory of the file when no workspace

README.md, package.json, src/ConfigService.ts, src/scm/Model.ts, src/test/suite/model.test.ts, test-fixtures/core/.vscode/settings.json
After merging #56 the thought occurred to me that it would still make sense to have an optional prompt to confirm that the user wants to submit a saved changelist (i.e. one that already has a changelist number) - because previously this would always try to submit without any confirmation.
Does not apply to the default changelist because we already have to prompt for a changelist description
=> Option to prompt before submit

src/ConfigService.ts, src/FileSystemActions.ts, src/PerforceCommands.ts, src/extension.ts, src/test/suite/fileSystemActions.test.ts, test-fixtures/core/.vscode/settings.json, test-fixtures/core/testFolder/subFolder/subFile, test-fixtures/core/testFolder/subFolder/subFile2, test-fixtures/core/testFolder/subFolder/underSubFolder/subSubFile
Check whether the deleted file is a directory before deleting.
It it is a directory, use the wildcard specifier to try to revert and delete the files
* Move event configuration into the ConfigAccessor
* Add some tests for FileSystemActions (incomplete)
Fixes #60
=> Delete with wildcard when folder delete event is received

README.md, src/ContentProvider.ts, src/ContextVars.ts, src/Display.ts, src/Utils.ts, src/api/CommandUtils.ts, src/api/PerforceApi.ts, src/extension.ts, src/scm/Model.ts, src/test/helpers/StubPerforceModel.ts, src/test/suite/model.test.ts, src/test/suite/perforceApi.test.ts
Changed Display from runnng `opened` directly, to using an api call to get opened files
This required the ability to parse stderr to determine the details of not open files
Added a `raw` method to the `makeSimpleCommand` return value to support this
Removed Utils.runCommand and changed the remaining call in the ContentProvider
=> Add context variables and commands for current file details

src/api/PerforceApi.ts, src/test/suite/perforceApi.test.ts
Perforce throws an error if the change spec contains an empty field at the end, without any newlines
This could happen if the default change spec was customised
Fixes #74
=> Correct parsing of changespec fields and add newlines at end of input

package.json, src/ContextVars.ts, src/PerforceCommands.ts, src/extension.ts
Adds a command that edits and saves the currently opened file.
Will fall back to the standard save command if there is no open editor (not sure that it *does* anything, but it will run it!)
Will always save the file even if the edit command fails
The command is always registered, in case of a workspace where activation mode is set to never
Also fixes an issue where recently added context variables didn't work!
fixes #72
=> Add edit and save command

package.json, src/ContentProvider.ts, src/ContextVars.ts, src/DiffProvider.ts, src/Display.ts, src/PerforceCommands.ts, src/PerforceService.ts, src/PerforceUri.ts, src/ScmProvider.ts, src/Utils.ts, src/annotations/AnnotationProvider.ts, src/annotations/MarkdownGenerator.ts, src/api/CommandUtils.ts, src/api/PerforceApi.ts, src/scm/Model.ts, src/scm/Resource.ts, src/test/helpers/StubPerforceModel.ts, src/test/helpers/helpers.d.ts, src/test/helpers/p4Commands.ts, src/test/helpers/testUtils.ts, src/test/suite/diffProvider.test.ts, src/test/suite/model.test.ts, src/test/suite/perforceCommands.test.ts, src/test/suite/perforceUri.test.ts, src/test/suite/utils.test.ts
Adds next and previous buttons to the editor title context.
To support this, Perforce URI handling was moved to a separate module, and more information is encoded in the URI when performing a diff:
* The URI of the left document is encoded in the query of the right doc
* This is because the context buttons always operate on the right hand doc with no information about the left hand doc
* The URI of the starting document for the diff is encoded so that 'diff next' works once we reach the have revision
* The have revision is encoded so that we know when we have reached the have revision when diffing next
Resources have slightly more sensible URIs that are more useful 'by default' which slightly simplifies the diff handling
The buttons can be enabled on all diffable files (uses the context …
=> Diff next and previous

src/PerforceCommands.ts
Automatically refresh on successful logon only - generally, the user would want an up to date scm provider, so there's no need to make them do it manually!
=> Automatically refresh the scm provider on login

src/FileSystemActions.ts, src/PerforceCommands.ts, src/PerforceService.ts
The delete directory command was trying to run from the directory that had already been deleted, which failed
Pass in the parent directory instead
=> Catch file check errors. Auto-delete from containing directory

README.md, package.json, src/ScmProvider.ts, src/extension.ts
Automatically creates SCM providers when a file is opened outside of an existing known client and disposes it again when all relevant files are closed
Keep track of which:
* individual documents
* directories (workspace or p4config dirs)
were used to create or keep an scm provider alive
Removes provider when none are left
Adds option to enable / disable activation and deactivation
May also add an option to re-activate the extension instead of forcing the user to reload, but this may be better off in a separate PR / issue
fixes #78 
fixes #89
=> Initialise scm providers when opening docs

src/PerforceUri.ts, src/test/helpers/p4Commands.ts, src/test/suite/model.test.ts, src/test/suite/perforceUri.test.ts
encodes the depot name as a URI component.
Fixes an issue where the depot path contains upper case characters - VS code URI parses them to lower case
fixes #97
=> Use correct case when reading the depot path from a depot URI

src/ContextVars.ts, src/DiffProvider.ts, src/Display.ts, src/PerforceUri.ts, src/annotations/AnnotationProvider.ts, src/api/CommandUtils.ts, src/test/suite/model.test.ts, src/test/suite/perforceUri.test.ts
* Checks if the file being annotated is the same as the active editor and if so sets the visible range in the new editor to match the existing one
* Encode the revision in to the query in URIs - not reading it currently, but vs code was (correctly) treating URIs with the same path but different fragments as the same file and not opening a new version
* This meant that if you had a depot file open and chose to annotate a different revision it would apply the annotations to the open revision instead of opening a new document
* Preferably any uses that rely on the `fsPath` or `fragment` of the URI should be replaced with calls to `PerforceUri` functions so we have centralised control of URI encoding and decoding - I would ultimately like to encode the revision with the '#' into the `fsPath` …
=> Maintain position when annotating a file

src/ScmProvider.ts
* different hostnames can resolve to the same server
* VS code can't actually handle two SCM providers with the same directory anyway, so we just ended up with an invisible provider adding to the count and running double commands
* (arguably, we could just use client root as the only differentiator... one to consider)
=> Remove check for same server address

src/extension.ts
- Running them together causes a lot of problems
- Shows a warning that can be permanently hidden
=> Add check to ensure slevesque version is not running

src/extension.ts
- When the check finds there is both,
- and the user clicks "Show installed",
- Focuses specifically on the extensions in the extension view
=> Focus on slevesque / mjcrouch extensions

src/TsUtils.ts, src/api/commands/basicOps.ts, src/quickPick/ChangeQuickPick.ts, src/quickPick/QuickPickProvider.ts, src/quickPick/QuickPicks.ts, src/scm/Model.ts, src/test/helpers/StubPerforceModel.ts, src/test/suite/model.test.ts, src/test/suite/perforceApi.test.ts
Adds option to the changelist quick pick to unshelve a changelist if it contains shelved files
* Into a changelist
* Into a changelist, via a branch mapping - not hugely useful *yet* as you still need to resolve after this kind of unshelve
* Parses the unshelve output
* Shows a warning if files require resolve
Think the code needs some tidy up - could possibly have a better format for the parsed output. Should also apply the same check for unresolved files in the scm unshelve view, which I'll probably include in this PR
Fixes #103
=> Unshelve other changelists

README.md, package.json, resources/icons/dark/status-unresolved-add.svg, resources/icons/dark/status-unresolved-archive.svg, resources/icons/dark/status-unresolved-branch.svg, resources/icons/dark/status-unresolved-delete.svg, resources/icons/dark/status-unresolved-edit.svg, resources/icons/dark/status-unresolved-integrate.svg, resources/icons/dark/status-unresolved-lock.svg, resources/icons/dark/status-unresolved-move.svg, resources/icons/light/status-unresolved-add.svg, resources/icons/light/status-unresolved-archive.svg, resources/icons/light/status-unresolved-branch.svg, resources/icons/light/status-unresolved-delete.svg, resources/icons/light/status-unresolved-edit.svg, resources/icons/light/status-unresolved-integrate.svg, resources/icons/light/status-unresolved-lock.svg, resources/icons/light/status-unresolved-move.svg, src/ConfigService.ts, src/PerforceService.ts, src/ScmProvider.ts, src/api/CommandUtils.ts, src/api/commands/basicOps.ts, src/quickPick/ChangeQuickPick.ts, src/scm/DecorationProvider.ts, src/scm/Model.ts, src/scm/Resource.ts, src/test/suite/model.test.ts, src/test/suite/perforceApi.test.ts
Adds red outline to icon when a file is unresolved
Adds commands to resolve a changelist or re-resolve a changelist if it contains unresolved / reresolvable files
Adds buttons on warning prompts, when a file needs resolving, to run the resolve for that changelist / file
This just shows the command line using a task, rather than providing any more parsing etc -  I can't really find a good way of handling the resolve programatically, other than parsing the input, sending output, parsing input, sending output etc. - unless it's just auto-merging, which is not always useful. This seems like the simplest way to report the progress and allow the user to make choices for now
Need https://github.com/microsoft/vscode/pull/90952 to be merged before doing resolve for individual files from the scm …
=> Show & resolve unresolved files

package.json, src/ContextVars.ts, src/DiffProvider.ts, src/PerforceCommands.ts, src/test/suite/diffProvider.test.ts
* This caused problems in various places such as remote-SSH and cpp extension
* Instead, use `isInDiffEditor` context vars to work out what to do
* when already diffing previous from the right hand diff editor, skip a revision, to diff have vs have -1
* Behaviour is slightly more limited when diffing previous from a working file diff
* (will diff against have -1 vs have instead of left -1 vs left unless the left window is clicked first)
* Moved some logic out of ts into package json
Fixes #118 
Probably fixes #119
=> Don't add query params to file: URIs when diffing

src/search/ChangelistTreeView.ts
Fixes problem clicking on a file when looking at a changelist focused from the quick pick
=> Use correct resource URI for file results

src/ConfigService.ts, src/TsUtils.ts, src/annotations/AnnotationProvider.ts, src/quickPick/FileQuickPick.ts
* When a filelog has a change with multiple sources, run more filelog commands to expand them out
* Improve complexity of annotation by caching stuff by change number - previously O(n*m) for combination of filelog length and file length
* Don't stop the whole annotation when one change is missing (in case of other unknown cases)
Also, correctly show all source revisions in the file history quick pick when there are multiple
fixes #120
=> Fix annotations for revisions with multiple source files

src/DiffProvider.ts
Prevents issues with query on file: URIs
fixes #119 (again)
=> Don't add query params on scm diff

README.md, package.json, src/ContentProvider.ts, src/Display.ts, src/PerforceCommands.ts, src/TsUtils.ts, src/api/commands/filelog.ts, src/extension.ts, src/quickPick/FileQuickPick.ts
* status bar menu - sync file, sync revision
* file quick pick - sync revision
* explorer context menu - sync file, sync directory
* Supports multi select
* For files, splits into directories and syncs all files in a dir together
* For dirs, one sync per directory
* Adds option to control whether to show explorer context
* remove line breaks in status bar messages
* makes them readable if multi-line
Attempts to notify content provider when have revision changes so that the gutter diffs are updated. Can't reasonably do this for all cases though, e.g. directory syncs and syncs from the quick pick
fixes #123
=> Add sync commands to various locations

package.json, src/PerforceCommands.ts, src/api/commands/basicOps.ts, src/test/helpers/StubPerforceModel.ts, src/test/suite/perforceCommands.test.ts
`Adds move / rename to the explorer context menu and status bar menu
* If multiple files or directories are selected, they must all be in the same dir, and the command moves the selected files to a different directory
* If a single file or directory is selected, the command renames it
* In either case, for a directory being moved it uses wildcards to move all children
* In all cases it opens the file (or wildcarded files) for edit, ignoring errors, and then opens them for move (without the -r) - this seems like it should cover cases where the file is already open or not open yet
* When moving a single file, if the file being moved is the active editor, then it opens the new file in the editor
Not sure about the setting name / description.
If we add more commands my thinking is the …
=> Add "move / rename" command

README.md, package.json, src/Display.ts, src/PerforceCommands.ts, src/api/commands/basicOps.ts, src/quickPick/FileQuickPick.ts, src/test/suite/perforceCommands.test.ts
* Also change to just one sync command instead of sync file / folder
* Add confirmation dialog to revert in status menu
* Also adds link to file history in status bar menu
~I think this still needs some tidying up wrt to selecting a mix of files and folders - the add / edit / revert currently only show when right clicking on a file, but if you select a folder and a file and then right click a file it will fail on the folders because they aren't wildcarded~
~This is probably ok - a bit safer than just allowing a whole directory to be reverted by accident, but think the bit where it consolidates passed in params could be updated to check if a directory is selected, stop the commands from running at-all and show a prompt~
~One option - allow directory command if a single dir is selected but …
=> Add "add / edit / revert" to explorer context menu

package.json, src/PerforceCommands.ts, src/api/CommandUtils.ts, src/api/commands/basicOps.ts
Controlled by `perforce.explorer.showFileOpCommands` setting
Also adds stdout logging for some basic commands add / edit / delete / revert / shelve / unshelve / sync
=> Add delete command to the explorer context menu

src/DiffProvider.ts, src/TreeView.ts, src/api/PerforceApi.ts, src/quickPick/ChangeQuickPick.ts, src/quickPick/FileQuickPick.ts, src/quickPick/QuickPicks.ts, src/quickPick/ShelvedFileQuickPick.ts, src/scm/Status.ts, src/search/ChangelistTreeView.ts, src/test/suite/diffProvider.test.ts
* Allows shelved file to be viewed, diffed against source revision, diffed against workspace revision
* Also adds shelved files to the changelist search results
Fixed some minor issues with diff titles (e.g. path/file1.txt vs path/file2.txt previously resulted in "1.txt vs 2.txt", shelved revision was showing as file#@=123)
=> Add quick pick for individual shelved files

package.json, src/PerforceCommands.ts, src/quickPick/ChangeQuickPick.ts, src/quickPick/FileQuickPick.ts, src/quickPick/QuickPickProvider.ts
* show pending / submitted status on changelist quick pick
* ability to show / hide newer revisions when choosing or diffing a revision
* add quick pick title to the quick pick itself to avoid confusion with the back button
* add command to open last quick pick without having to find a random revision
* also adds a variety of keyboard shortcuts
=> Quick pick improvements

package.json, src/Display.ts, src/ScmProvider.ts, src/api/PerforceApi.ts, src/api/SpecParser.ts, src/api/commands/changeSpec.ts, src/api/commands/job.ts, src/quickPick/ChangeQuickPick.ts, src/quickPick/FileQuickPick.ts, src/quickPick/JobQuickPick.ts, src/quickPick/QuickPickProvider.ts, src/quickPick/QuickPicks.ts, src/scm/Model.ts, src/search/ChangelistTreeView.ts
* Shows the list of changelists that fix the job etc.
* Common function for clipboard operations
* now reopens the quick pick after copying
* add 'fixes' and 'job' commands to API
* add "go to job" and "go to changelist" to the scm provider
* if run from the command palette and there are multiple scm providers, asks for one first
* make loginScm the default from the command palette so it can prompt
=> Add job quick pick

src/ComboBoxInput.ts, src/api/CommandUtils.ts, src/api/PerforceApi.ts, src/api/commands/client.ts, src/api/commands/users.ts, src/search/Filters.ts
Uses a custom quick pick input to accept typed input as well as choosing an option
e.g. when entering a client, the user is presented with the options:
* Current user
* Enter a user
* Reset filter
Previously to enter a custom user, this required clicking on "enter a user" and then entering the value
Now when the user starts typing, the "enter a user" item changes into one that represents the value being typed.
This also applies to the "client" and "files" filters.
For the "client" and "user" filters, if * is entered in the value then it performs a search for those items
=> Combo box for changelist search filters

src/api/PerforceApi.ts, src/api/commands/branch.ts, src/quickPick/ChangeQuickPick.ts
When unshelving through a branch mapping, using * in the path instructs it to look for matching branches
=> Add branch search when unshelving

package.json, src/PerforceCommands.ts, src/ScmProvider.ts, src/SpecEditor.ts, src/api/commands/changeSpec.ts, src/api/commands/job.ts, src/extension.ts, src/quickPick/ChangeQuickPick.ts, src/quickPick/JobQuickPick.ts, src/scm/Model.ts
Adds commands to changelist and job quick picks, and the scm provider for changelists
Opens a change or job spec in the editor, then prompts to upload the modified spec when it is saved.
To do this it creates a temporary file in the local storage area, and uses the extension Memento to store a mapping of file to workspace path (so we know which resource URI to pass in to the API when applying the updates)
~TODO - currently nothing deletes the files or memento entries - though this is probably not hugely significant (even thousands of files will probably not have any significant impact), it's not ideal for them to build up.~
* ~Not really an option to delete on file close, because even after closing an editor it can be reopened.~
* ~Could add a last accessed time to the memento and delete …
=> Add ability to edit change and job specs

package.json, src/ScmProvider.ts, src/SpecEditor.ts, src/api/commands/job.ts, src/scm/Model.ts
Adds "Create changelist in editor..." and "Create job in editor..." to scm navigation menu
Runs `p4 change -o` / `p4 job -o` without a parameter to get default spec
For a new item, closes the 'new' editor and reopens with the new changelist / job id
=> Create new changelist and jobs using the spec editor

package.json, src/ConfigService.ts, src/scm/Model.ts
new mode hides non workspace files in the default changelist, and hides all changelists that have ONLY non-workspace files.
Made the names a big shorter and used enumDescriptions - should be backward compatible with any customisations
Fixes / updated a bunch of other minor config issues
=> Additional mode for hide non workspace files

src/DiffProvider.ts, src/FileSystemActions.ts, src/PerforceCommands.ts, src/PerforceUri.ts, src/ScmProvider.ts, src/api/CommandUtils.ts, src/api/CommonTypes.ts, src/api/commands/basicOps.ts, src/quickPick/FileQuickPick.ts, src/quickPick/QuickPickProvider.ts, src/quickPick/ShelvedFileQuickPick.ts, src/scm/Model.ts, src/scm/Resource.ts, src/search/Filters.ts, src/test/helpers/p4Commands.ts, src/test/helpers/testUtils.ts, src/test/suite/diffProvider.test.ts, src/test/suite/model.test.ts, src/test/suite/perforceApi.test.ts, src/test/suite/perforceCommands.test.ts, src/test/suite/perforceUri.test.ts
* This allows the revision to be displayed in the editor title when a specific revision is opened
* Affects a lot of areas that used fsPath
* don't include revision in resource URIs on the scm provider
* prevents @= labels on shelved files (though, this isn't necessarily bad...)
* instead, an `openUri` param is stored in the Resource which is the one to open for diffs etc.
* Add helper PerforceUri functions to get various bits of URIs
* Messes with the parsing since # is the fragment identifier, so a new parse function is added that sorts it out
~TODO: can possibly now remove filespec type that's just an fsPath~
~might be a good idea to remove all references to `resourceUri` so that we can change how items are displayed in the scm provider without affecting any other behaviour~
=> Include revision in the path for perforce URIs

package.json, src/ContentProvider.ts, src/FileSystemProvider.ts, src/PerforceCommands.ts, src/PerforceUri.ts, src/annotations/AnnotationProvider.ts, src/annotations/MarkdownGenerator.ts, src/extension.ts, src/test/helpers/testUtils.ts, src/test/suite/index.ts, src/test/suite/model.test.ts, src/test/suite/perforceApi.test.ts, src/test/suite/perforceCommands.test.ts, src/test/suite/perforceUri.test.ts, src/test/suite/unit/index.ts, test-fixtures/core/.vscode/settings.json
Allows perforce revisions to be displayed in the header without affecting the file path, so syntax highlighting works
This uses the `resourceLabelFormatters` option - which only supports `FileSystemProvider` (not TextDocumentContentProvider) and has a limited number of variables that can be used
As such we do have to rewrite the `authority` of the URI so that we can display it after the file name - but as the previous implementation changed all the usages of possible perforce URIs to use common functions, this is reasonably trivial.
~TODO - rename content provider file~
Perforce URI might need a little tidying up when I read over the code again...
=> Replace content provider with FileSystemProvider, display file revisions

src/FileSystemProvider.ts, src/PerforceUri.ts, src/test/suite/model.test.ts
Fixes error opening diff for files open for add
(the `FileSystemProvider` doesn't accept relative paths, and just throws an error instead)
fixes #156
=> Add slash to the beginning of the "EMPTY" path

package.json
Not adding new functionality - this is just easier to use if the search view is very wide, rather than having to scan across the whole row
=> Add right click context commands to changesearch items

package.json, src/MementoItem.ts, src/extension.ts, src/search/ChangelistTreeView.ts, src/search/Filters.ts
Saves the filters + auto search setting in a memento for the workspace, so that filters are not forgotten between sessions.
~TODO - may want a command to clear the mementos in case of any bugs - could a dodgy memento state cause the search to fail to load properly and is there a way out of it?~
=> Persist search filters in a memento

src/FileSystemProvider.ts, src/PerforceUri.ts, src/quickPick/JobQuickPick.ts, src/test/suite/perforceUri.test.ts
Fixes issue with filesystem provider not being able to use relative URIs
Also add whitelist to prevent arbitrary commands from being run
fixes #162
=> Use an absolute URI for displaying command output

.vscode/settings.json, src/extension.ts
when intialising workspace, the check for whether one dir is in another now ignore case, if p4 info tells us the server is not case sensitive.
I _think_ this is the only place that needs changing - in other locations, generally we're either working with what the command line gives us and those paths should be correct, or we're working with local file paths which the server should interpret correctly if it is case insensitive.
I also believe this applies equally to linux and windows clients - the insensitivity is done by perforce, not by the OS.
Tested on windows with case insensitive and case sensitive server - case sensitive server correctly did **not** create a workspace when the case was different. Case insensitive server correctly **did** create a worskpace
fixes #164
=> Don't check case for case-insensitive servers

package.json
This is the string that appears as the name of the extension in the sidebar in Settings under _Extensions_. Long configuration names are discouraged as they are usually clipped. Additionally, the config name should not contain "VS Code", namely because it will sort it with the rest of the V's while users will expect a Perforce extension to be near the rest of the P's in this list.
=> Shorten extension configuration name

README.md, package.json, src/ConfigService.ts, src/ScmProvider.ts, src/scm/Model.ts
- uses contributing dirs to work out which dirs in the workspace are relevant - that is, the set of dirs where we detected a perforce client. So, it should work when the perforce client was found underneath the workspace, using a p4config, and it should work when the client is above, because we detect it from the workspace root.
- if there are no contributing dirs, we auto-detected from a single file
- in this case, we just sync the whole perforce client
There is a caveat that it probably won't work if you force activation of the scm provider even when it doesn't relate to your vs code workspace at-all
I did consider adding in a "sync workspace" option on to the menu as well, however, I think this would get confusing if the client is auto detected from a client outside of the workspace - …
=> Add option to sync the workspace folder only

package.json, src/ScmProvider.ts
Only enabled for right click on scm provider.
This is a basic implementation so far - still need to consider some options for whether to force things to go away and not come back.
I think this is actually slightly nicer than the git implementation currently - In the git version, just opening an editor tab that has a file in a repo will always re-activate the repo. Currently as in this PR it won't re-open until you open a new file in the perforce client.
Fixes #174
=> Add command to close a perforce client

package.json, src/ScmProvider.ts, src/scm/Model.ts
- Prevents minimised groups expanding on refresh
- Keep existing resource groups and just update with new files as necessary
- Change to use new 'in' operator of when clause for resolve / re-resolve
- This keeps group ids consistent so we don't need to re-create them when the resolve state changes
Note that, in the case where a refresh results in a new changelist, we still have to fully clean and recreate the pending changelists. This is because they always appear on the scm view in the order they are added, so new changelists come out at the bottom of the scm view, but the default sort order for the extension is to put newer changelists at the top - so we need to recreate everything to get them in the right order.
Probably needs a bit more testing. Might want to force the refresh button …
=> Don't clean groups on refresh

package.json, src/PerforceService.ts, src/ScmProvider.ts, src/scm/Model.ts, src/scm/Resource.ts, src/test/suite/model.test.ts
Now that my PR has been merged in vs code, we are able to use context about specific files in when clauses. The actual API is not expected to be finalised until September VS Code release (which happens in October) - so, while this would work as is, even without the finalised API or any workarounds, it is best to wait until the API is finalised before merging this PR.
This PR mainly concerns the difference between shelved / normal files. For example:
- We no longer see "Delete shelved file" on a file that is not shelved
- But we do see a new delete $(trash) icon on the inline menu for shelved files
- We no longer see "Revert", or "Move to changelist" on a shelved file
- We no longer need a combined command to shelve or unshelve a file (along with its mysterious "pair of files" icon on the …
=> Tidy up scm context menus

package-lock.json, package.json, src/TreeView.ts, src/scm/DecorationProvider.ts, src/scm/Model.ts, src/search/ChangelistTreeView.ts, src/search/Filters.ts
Implements the `FileDecorationProvider` api that was added in vscode 1.52
Creates a bunch of new theme colors that inherit from the git colors that represent similar concepts
Ups minimum version to 1.53 - there were some API changes to the tree view in 1.52 that also needed minor handling
fixes #201
=> Add file decorations to the explorer

src/scm/Model.ts
- previously updated to re-use changelist objects for cleaner refresh
- however, forgot to remove from collection
- this caused the badge count on scm to be too high after submitting a changelist
- also caused old changelists to be visible in the move quick pick
fixes #205
=> Remove unused changelists after submission or deletion

src/api/commands/describe.ts, src/scm/Model.ts
Previously the job input was expecting only letters and numbers,
however other non whitespace characters are also allowed
Also updated the parsing of changelists to handle other non-ws chars
fixes #208
=> Don't validate job name input

src/PerforceUri.ts
A special value is used where a URI is just for printing command output
This wasn't handled when getting the workspace, therefore the job output wasn't working
=> fix workspace detection for command-only URIs

src/CommandLimiter.ts, src/Display.ts, src/PerforceService.ts, src/api/CommonTypes.ts, src/test/suite/unit/CommandLimiter.test.ts
fixes #234
- Properly handle errors from async operations in command limiter
- Editor uri has fsPath='' which wasn't being considered as a URI, leading to an exception when trying to log the command to be run. Updated the isUri check to handle empty fsPath
- Don't get status for any URIs with an empty fsPath since they don't make sense anyway
=> fix command limiter bottlenecking when opening search in editor

src/PerforceCommands.ts
Fixes #236 
- Run the where command using the resource that the opened command uses
=> fixed opening files from "opened" quick pick command

package.json, src/PerforceService.ts
Enabling the setting logs all perforce commands and their output in to the console
Format is:
Running a command:
`[P4 RUN] <unique id> <cmd> <args> <spawn args>`
spawn args will include things like the env variables in the shell
Results:
`[P4 RES] <same unique id> <stdin> <stderr>`
Or
`[P4 ERR] <same unique id> <exception>`
if there was an exception
=> Add debugP4Commands setting

src/test/suite/perforceCommands.test.ts
For some reason this test takes ages on mac, increasing the timeout so that the test runs don't all get marked as broken
=> increase timeout for test that times out on mac

src/PerforceService.ts
Problem:
Perforce workspaces are not detected when symbolic link of client root opened from editor. This happens because "isDirectory" function evaluation does not accept symbolic link directories, so, the cwd is taken only up to the previous directory of the symbolic link. As a result, All the p4 commands (e.g p4 info) executed at different path, leading to workspaces not being detected.
e.g: /user/jan/p4_link-->/user/jan/p4_workspace
currently, operations are working fine when using ""/user/jan/p4_workspace". However, workspace is not detected when the symbolic link "/user/jan/p4_link" used.
Solution:
I've added a symbolic directory evaluation when deciding cwd. 
@mjcrouch Can you please look into it?
=> Evaluate symbolic link directory in cwd

src/PerforceUri.ts, src/test/suite/model.test.ts, src/test/suite/perforceUri.test.ts
Fixes #260 
To format the editor title with the depot revision we use the authority (with # and @= - for example if the depot path is `//depot/my/file#2` then we would parse that to a URI something like `perforce://#2/my/file?depot=true&depotName=depot&rev=2#2`) - this is specified in the package.json `resourceLabelFormatters` where we don't have the ability to parse the query string and we don't receive the fragment (IIRC)
However, this results in technically illegally encoded URIs that don't meet the RFC. We generally get away with it, but it causes the C# extension to break when parsing the URIs (i.e. whenever you open any editor)
Replacing '#' with '-rev-' and '=' with 'shelved-' prevents such errors because the - is valid in the authority.
This does mean that titles are now displayed …
=> Fixes illegal URI formatting for perforce URIs
